data_headers_dict = {
    "DIA": 0,
    "MES": 0,
    "temporada_alta": 0,
    "DIANOM_Domingo": 0,
    "DIANOM_Jueves": 0,
    "DIANOM_Lunes": 0,
    "DIANOM_Martes": 0,
    "DIANOM_Miercoles": 0,
    "DIANOM_Sabado": 0,
    "DIANOM_Viernes": 0,
    "TIPOVUELO_I": 0,
    "TIPOVUELO_N": 0,
    "OPERA_Aerolineas Argentinas": 0,
    "OPERA_Aeromexico": 0,
    "OPERA_Air Canada": 0,
    "OPERA_Air France": 0,
    "OPERA_Alitalia": 0,
    "OPERA_American Airlines": 0,
    "OPERA_Austral": 0,
    "OPERA_Avianca": 0,
    "OPERA_British Airways": 0,
    "OPERA_Copa Air": 0,
    "OPERA_Delta Air": 0,
    "OPERA_Gol Trans": 0,
    "OPERA_Grupo LATAM": 0,
    "OPERA_Iberia": 0,
    "OPERA_JetSmart SPA": 0,
    "OPERA_K.L.M.": 0,
    "OPERA_Lacsa": 0,
    "OPERA_Latin American Wings": 0,
    "OPERA_Oceanair Linhas Aereas": 0,
    "OPERA_Plus Ultra Lineas Aereas": 0,
    "OPERA_Qantas Airways": 0,
    "OPERA_Sky Airline": 0,
    "OPERA_United Airlines": 0,
    "SIGLAORI_Santiago": 0,
    "SIGLADES_Antofagasta": 0,
    "SIGLADES_Arica": 0,
    "SIGLADES_Asuncion": 0,
    "SIGLADES_Atlanta": 0,
    "SIGLADES_Auckland N.Z.": 0,
    "SIGLADES_Balmaceda": 0,
    "SIGLADES_Bariloche": 0,
    "SIGLADES_Bogota": 0,
    "SIGLADES_Buenos Aires": 0,
    "SIGLADES_Calama": 0,
    "SIGLADES_Cancun": 0,
    "SIGLADES_Castro (Chiloe)": 0,
    "SIGLADES_Cataratas Iguacu": 0,
    "SIGLADES_Ciudad de Mexico": 0,
    "SIGLADES_Ciudad de Panama": 0,
    "SIGLADES_Cochabamba": 0,
    "SIGLADES_Concepcion": 0,
    "SIGLADES_Copiapo": 0,
    "SIGLADES_Cordoba": 0,
    "SIGLADES_Curitiba, Bra.": 0,
    "SIGLADES_Dallas": 0,
    "SIGLADES_Florianapolis": 0,
    "SIGLADES_Guayaquil": 0,
    "SIGLADES_Houston": 0,
    "SIGLADES_Iquique": 0,
    "SIGLADES_Isla de Pascua": 0,
    "SIGLADES_La Paz": 0,
    "SIGLADES_La Serena": 0,
    "SIGLADES_Lima": 0,
    "SIGLADES_Londres": 0,
    "SIGLADES_Los Angeles": 0,
    "SIGLADES_Madrid": 0,
    "SIGLADES_Melbourne": 0,
    "SIGLADES_Mendoza": 0,
    "SIGLADES_Miami": 0,
    "SIGLADES_Montevideo": 0,
    "SIGLADES_Neuquen": 0,
    "SIGLADES_Nueva York": 0,
    "SIGLADES_Orlando": 0,
    "SIGLADES_Osorno": 0,
    "SIGLADES_Paris": 0,
    "SIGLADES_Pisco, Peru": 0,
    "SIGLADES_Puerto Montt": 0,
    "SIGLADES_Puerto Natales": 0,
    "SIGLADES_Puerto Stanley": 0,
    "SIGLADES_Punta Arenas": 0,
    "SIGLADES_Punta Cana": 0,
    "SIGLADES_Punta del Este": 0,
    "SIGLADES_Quito": 0,
    "SIGLADES_Rio de Janeiro": 0,
    "SIGLADES_Roma": 0,
    "SIGLADES_Rosario": 0,
    "SIGLADES_San Juan, Arg.": 0,
    "SIGLADES_Santa Cruz": 0,
    "SIGLADES_Sao Paulo": 0,
    "SIGLADES_Sydney": 0,
    "SIGLADES_Temuco": 0,
    "SIGLADES_Toronto": 0,
    "SIGLADES_Tucuman": 0,
    "SIGLADES_Ushuia": 0,
    "SIGLADES_Valdivia": 0,
    "SIGLADES_Washington": 0,
    "periodo_dia_mañana": 0,
    "periodo_dia_noche": 0,
    "periodo_dia_tarde": 0,
}
